### ISSUE TITLE
Issue with sudo make install

### ISSUE THREAD

**Issue by bcallaughan** [juhovh/xmm7360_usb#4]
I'm trying to get this working on my X1 Carbon Gen 7 running Linux Mint, I get the following when issuing sudo make install
`
make -C /lib/modules/4.15.0-66-generic/build M=/home/brett/Downloads/xmm7360_usb modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-66-generic'
  INSTALL /home/brett/Downloads/xmm7360_usb/xmm7360_usb.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.15.0-66-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-66-generic'
`

**Comment by juhovh** [comment]
This is actually not a fatal error, it fails to sign the module but compilation and installation should still work.

**Comment by bcallaughan** [comment]
Here is the complete output

`brett@HSVGTS:~$ git clone https://github.com/juhovh/xmm7360_usb.git
Cloning into 'xmm7360_usb'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 2), reused 10 (delta 2), pack-reused 0
Unpacking objects: 100% (10/10), done.
brett@HSVGTS:~$ ls
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos  xmm7360_usb
brett@HSVGTS:~$ cd xmm7360_usb/
brett@HSVGTS:~/xmm7360_usb$ ls
LICENSE.txt  Makefile  README.md  xmm7360_usb.c
brett@HSVGTS:~/xmm7360_usb$ make
make -C /lib/modules/4.15.0-66-generic/build M=/home/brett/xmm7360_usb modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-66-generic'
  CC [M]  /home/brett/xmm7360_usb/xmm7360_usb.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/brett/xmm7360_usb/xmm7360_usb.mod.o
  LD [M]  /home/brett/xmm7360_usb/xmm7360_usb.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-66-generic'
brett@HSVGTS:~/xmm7360_usb$ sudo make install
[sudo] password for brett:              
make -C /lib/modules/4.15.0-66-generic/build M=/home/brett/xmm7360_usb modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-66-generic'
  INSTALL /home/brett/xmm7360_usb/xmm7360_usb.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.15.0-66-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-66-generic'
brett@HSVGTS:~/xmm7360_usb$ sudo modprobe xmm7360_usb 
modprobe: FATAL: Module xmm7360_usb not found in directory /lib/modules/4.15.0-66-generic
brett@HSVGTS:~/xmm7360_usb$ 

`
